name: 🔨 Build Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: build image
        uses: docker/build-push-action@v5
