name: 🎉 Release Binary
on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs: 
  release: 
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            fopina/protonvpn:${{ steps.prepare.outputs.tag_name }}
            ghcr.io/fopina/protonvpn:${{ steps.prepare.outputs.tag_name }}
            fopina/protonvpn:latest
            ghcr.io/fopina/protonvpn:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
